### ISSUE TITLE
AGPL?

### ISSUE THREAD

**Issue by pryme-svg** [devnote-dev/Radeon#28]
Currently, this project is licensed under the GPL-3.0. However, there is a loophole in the GPL that allows distributors to close-source their software if a user is only interacting with it through a network, as they do not receive a copy of the program to run. See https://www.gnu.org/licenses/why-affero-gpl.en.html. This means that other developers are able to take your code and incorporate it into another proprietary discord bot, which may not be desirable. However, this is patched in the AGPL-3.0, which you may want to switch to.

**Comment by devnote-dev** [comment]
Fixed in PR #29, thanks for the heads up 👍
